board/urls.py
from django.urls import path
from board import views

app_name = 'board'
urlpatterns = [
    path('', views.board, name='board'),
    path('<int:pk>/', views.BoardDetailView.as_view(), name='board'),
    path('create_board/', views.create_board, name='create_board'),
    path('update_board/<int:board_id>/', views.update_board, name='update_board'),
    path('delete_board/<int:board_id>/', views.delete_board, name='delete_board'),
]

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.home, name='home'),
    path('add/', views.add_cart, name='add'),
    path('delete/<int:cart_id>/', views.delete_cart, name='delete'),
    path('update/<int:cart_id>/', views.update_cart, name='update'),
    path('update_order/', views.update_order, name='update_order'),
    path('check_order/', views.check_order, name='check_order'),
    path('check_done/', views.check_done, name="check_done"),
    path('orders/', views.order_home, name='orders'),
    path('order/<int:order_id>', views.order_read, name='order_read'),
    path('order_delete/<int:order_id>', views.order_delete, name='order_delete'),
    path('ship/', views.ship_api, name='ship')
]

coffee_shop/urls.py
from django.contrib import admin
from django.urls import path, include #re_path
from main import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.main, name='main'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('product/', include('product.urls', namespace='product')),
    path('board/', include('board.urls', namespace='board')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('contact/', include('contact.urls', namespace='contact')),
    #re_path('.*', views.main),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models


class Board(models.Model):
    title = models.CharField(max_length=128, unique=True)
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-pub_time']

board/forms.py
from django import forms
from board.models import Board


class BoardForm(forms.ModelForm):
    title = forms.CharField(label='公告標題', max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
    content = forms.CharField(label='公告內容', widget=forms.Textarea(attrs={'class': 'form-control'}))
    # we don’t want to call it.
    # We just want a reference to the class that it belongs to, forms.Textarea not forms.Textarea()

    class Meta:
        model = Board
        fields = ['title', 'content']

board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import DetailView
from django.contrib import messages

from board.models import Board
from board.forms import BoardForm
from main.views import admin_required


class BoardDetailView(DetailView):
    queryset = Board.objects.all()
    template_name = 'board/try.html'


def board(request):
    '''
    get the board object and show on board page
    '''
    boards = Board.objects.all()
    return render(request, 'board/board.html', {'boards': boards})


@admin_required
def create_board(request):
    '''
    Create a new board instance
        1. If method is GET, render an empty form
        2. If method is POST, perform form validation and display error messages if the form is invalid
        3. Save the form to the model and redirect the user to the board page
    '''
    template = 'board/create_update_board.html'
    if request.method == "GET":
        return render(request, template, {'form': BoardForm()})

    # POST
    form = BoardForm(request.POST)
    if not form.is_valid():
        return render(request, template, {'form': form})
    form.save()
    messages.success(request, '公告已新增')
    return redirect('board:board')


@admin_required
def update_board(request, board_id):
    board = get_object_or_404(Board, id=board_id)
    template = 'board/create_update_board.html'
    if request.method == "GET":
        form = BoardForm(instance=board)
        return render(request, template, {'form': form})

    # POST
    form = BoardForm(request.POST, instance=board)
    if not form.is_valid():
        return render(request, template, {'form': form})
    form.save()
    messages.success(request, '公告已修改')
    return redirect('board:board')


@admin_required
def delete_board(request, board_id):
    if request.method == 'GET':
        return board(request)

    board = get_object_or_404(Board, id=board_id)
    board.delete()
    messages.success(request, '公告已刪除')
    return redirect('board:board')

board/templates/board/board.html
{% extends 'main/base.html' %}
{% load staticfiles %}

{% block heading %}公告{% endblock %}

{% block content %}
<section class="page-section about-heading">
  <div class="container">
    <img class="img-fluid rounded about-heading-img mb-3 mb-lg-0" src="{% static 'main/img/01.png' %}" alt="">
    <div class="about-heading-content">
      <div class="row">
        <div class="col-xl-10 col-lg-10 mx-auto">
          {% if user.is_staff %}
          <div class="bg-faded rounded p-5">
            <p><a class="btn btn-success" href="{% url 'board:create_board' %}">新增公告</a></p>
          </div>
          {% endif %}
          <br><br>
          {% for board in boards %}
          <div class="bg-faded rounded p-5">
            {% if user.is_staff %}
            <div class="inlineBlock">
              <a class="btn btn-info" href="{% url 'board:update_board' board.id %}">修改</a>
            </div>
            <div class="inlineBlock">
              <form class="inlineBlock" method="post" action="{% url 'board:delete_board' board.id %}">
                {% csrf_token %}
                <input class="btn btn-outline-danger deleteConfirm" type="submit" value="刪除">
              </form>
            </div>
            <br><br>
            {% endif %}
            <h3 class="section-heading mb-4">
              <span class="section-heading-upper">{{ board.pub_time|date:'Y-m-d H:i' }}</span>
            </h3>
            <hr>
            <h2>
              <span class="section-heading-lower">{{ board.title }}</span>
            </h2>
            {{ board.content|linebreaks }}
          </div>
          <br>
          <br>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

{% block script %}
<script src={% static 'main/js/confirm_delete.js' %}></script>
{% endblock %}

board/templates/board/create_update_board.html
{% extends 'main/base.html' %}
{% load staticfiles %}

{% block heading %}
  {% if board_form.instance.id %}
    修改公告
  {% else %}
    新增公告
  {% endif %}
{% endblock %}

{% block content %}
<section class="page-section">
  <div class="container">
    <div class="row">
      <div class="col-xl-9 col-lg-10 mx-auto">
        <div class="bg-faded rounded p-5">
          {% if form.instance.id %}
          <form method="post" action="{% url 'board:update_board' form.instance.id %}">
          {% else %}
          <form method="post" action="{% url 'board:create_board' %}">
          {% endif %}
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <input class="btn btn-primary" type="submit" value="送出">
            <a class="btn btn-outline-secondary" href="{% url 'board:board' %}">放棄</a>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}