cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.home, name='home'),
    path('add/', views.add_cart, name='add'),
    path('delete/<int:cart_id>/', views.delete_cart, name='delete'),
    path('update/<int:cart_id>/', views.update_cart, name='update'),
    path('update_order/', views.update_order, name='update_order'),
    path('check_order/', views.check_order, name='check_order'),
    path('check_done/', views.check_done, name="check_done"),
    path('orders/', views.order_home, name='orders'),
    path('order/<int:order_id>', views.order_read, name='order_read'),
    path('order_delete/<int:order_id>', views.order_delete, name='order_delete'),
    path('ship/', views.ship_api, name='ship')
]

coffee_shop/urls.py
from django.contrib import admin
from django.urls import path, include #re_path
from main import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.main, name='main'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('product/', include('product.urls', namespace='product')),
    path('board/', include('board.urls', namespace='board')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('contact/', include('contact.urls', namespace='contact')),
    #re_path('.*', views.main),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views

app_name = 'product'
urlpatterns = [
    path('', views.product, name='product'),
    path('create_product/', views.create_product, name='create_product'),
    path('read_product/<int:product_id>/', views.read_product, name='read_product'),
    path('update_product/<int:product_id>/', views.update_product, name='update_product'),
    path('delete_product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('search_product/', views.search_product, name='search_product'),
    path('create_comment/<int:product_id>/', views.create_comment, name='create_comment'),
    # path('update_comment/<int:comment_id>/', views.update_comment, name='update_comment'),
    path('delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
]

product/models.py
from django.urls import reverse
from django.db import models
from account.models import User

import os
import random


def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)  # '123.jpg'
    name, ext = os.path.splitext(base_name)  # ('123', '.jpg')
    return name, ext


def upload_image_path(instance, filename):
    # print(instance.title) -> model instance name
    new_filename = random.randint(1, 2323524012)
    name, ext = get_filename_ext(filename)
    final_filename = '{}{}'.format(new_filename, ext)
    return 'product/{}'.format(final_filename)


class Product(models.Model):
    title = models.CharField(max_length=128, unique=True)
    content = models.TextField(null=True, blank=True)
    price = models.IntegerField(default=300)
    # image = models.ImageField(upload_to=upload_image_path, default='product/2238217906.jpg', blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product:read_product', kwargs={'product_id': self.id})


class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    content = models.TextField(max_length=128)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['pub_time']

    def __str__(self):
        return self.product.title + '-' + str(self.id)

product/forms.py
from django import forms
from product.models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'content', 'price']
        labels = {
            'title': '商品名稱',
            'content': '商品描述',
            'price': '價錢',
        }
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
        }

product/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.db.models.query_utils import Q
from django.contrib.auth.decorators import login_required

from product.models import Product, Comment
from product.forms import ProductForm
from main.views import admin_required


def product(request):
    '''
    Render the product page
    '''
    products = Product.objects.all()
    return render(request, 'product/product.html', {'products': products})


@admin_required
def create_product(request):
    '''
    Create a new product instance
        1. If method is GET, render an empty form
        2. If method is POST, perform form validation and display error messages if the form is invalid
        3. Save the form to the model and redirect the user to the product page
    '''
    template = 'product/create_update_product.html'
    if request.method == 'GET':
        return render(request, template, {'productForm': ProductForm()})

    # POST
    productForm = ProductForm(request.POST)
    if not productForm.is_valid():
        return render(request, template, {'productForm': productForm})
    productForm.save()
    messages.success(request, '商品已新增')
    return redirect('product:product')


def read_product(request, product_id):
    '''
    Read product pages
        1. Get the "product" instance using "product_id"; redirect to the 404 page if not found
        2. Render the read_product template with the product instance and its
           associated comments
    '''
    product = get_object_or_404(Product, id=product_id)
    return render(request, 'product/read_product.html', {'product': product})


@admin_required
def update_product(request, product_id):
    '''
    Update the article instance:
        ...
    '''
    product = get_object_or_404(Product, id=product_id)
    template = 'product/create_update_product.html'
    if request.method == 'GET':
        productForm = ProductForm(instance=product)
        return render(request, template, {'productForm': productForm})

    # POST
    productForm = ProductForm(request.POST, instance=product)
    if not productForm.is_valid():
        return render(request, template, {'productForm': productForm})
    productForm.save()
    messages.success(request, '商品頁已修改')
    return redirect('product:read_product', product_id=product_id)


@admin_required
def delete_product(request, product_id):
    '''
    Delete the article instance:
        ...
    '''
    if request.method == 'GET':
        return product(request)
    # POST
    product = get_object_or_404(Product, id=product_id)
    product.delete()
    messages.success(request, '商品已刪除')
    return redirect('product:product')


def search_product(request):
    '''
    Search for articles:
        ...
    '''
    q = request.GET.get('q')
    qset = q.split()
    products = Product.objects.all()
    for qs in qset:
        products = products.filter(Q(title__icontains=qs) |
                                    Q(content__icontains=qs))
    return render(request, 'search/search_product.html', {'products': products, 'q': q})


@login_required
def create_comment(request, product_id):
    '''
    Create a comment for an article:
        1. Get the "comment" from the HTML form
        2. Store it to database
    '''
    if request.method == 'GET':
        return read_product(request, product_id)

    # POST
    comment = request.POST.get('comment')
    if comment:
        comment = comment.strip()
    if not comment:
        return redirect('product:read_product', product_id=product_id)
    product = get_object_or_404(Product, id=product_id)
    Comment.objects.create(product=product, user=request.user, content=comment)
    return redirect('product:read_product', product_id=product_id)


@login_required
def delete_comment(request, comment_id):
    '''
    Delete a comment:
        1. Get the comment to update and its product article; redirect to 404 if not found
        2. Delete the comment
    '''
    comment = get_object_or_404(Comment, id=comment_id)
    product = get_object_or_404(Product, id=comment.product.id)

    if request.method == 'GET':
        return read_product(request, product.id)

    # POST
    if comment.user != request.user:
        messages.error(request, '無刪除權限')
        return redirect('product:read_product', product_id=product.id)

    comment.delete()
    return redirect('product:read_product', product_id=product.id)

product/templates/product/create_update_product.html
{% extends 'main/base.html' %}

{% block heading %}
  {% if productForm.instance.id %}
    修改商品
  {% else %}
    新增商品
  {% endif %}
{% endblock %}
{% block content %}
<section class="page-section">
  <div class="container">
    <div class="row">
      <div class="col-xl-9 col-lg-10 mx-auto">
        <div class="bg-faded rounded p-5">
          {% if productForm.instance.id %}
          <form method="post" action="{% url 'product:update_product' productForm.instance.id %}">
          {% else %}
          <form method="post" action="{% url 'product:create_product' %}">
          {% endif %}
            {% csrf_token %}
            {{ productForm.as_p }}
            <input class="btn btn-primary mt-3" type="submit" value="送出">
            <a class="btn btn-outline-secondary mt-3" href="{% url 'product:product' %}">放棄</a>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

  {% endblock %}

product/templates/product/product.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block css %}
<link rel="stylesheet" href="{% static 'product/css/product.css' %}">
{% endblock %}
{% block heading %}商品{% endblock %}
{% block content %}

<!-- Page Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-4 col-md-6 mb-4 mt-5 ml-auto">
      {% include 'search/search_form.html' %}
    </div>

    <!-- /.col-lg-3 -->
    <div class="col-lg-12">
      <div class="row">
        {% if user.is_staff %}
        <div class="col-lg-4 col-md-6 mb-4">
          <div class="card h-100 bg-faded">
            <p><a class="btn btn-success" href="{% url 'product:create_product' %}">新增商品</a></p>
          </div>
        </div>
        {% endif %}
        {% for product in products %}
        <div class="col-lg-4 col-md-6 mb-4">
          <div class="card h-100 bg-faded">
            {% if user.is_staff %}
            <div class="row">
              <div class="col-2">
                <a href="{% url 'product:update_product' product.id %}" class="btn btn-info">修改</a>
              </div>
              <div class="col-2">
                <form method="post" action="{% url 'product:delete_product' product.id %}">
                  {% csrf_token %}
                  <input class="btn btn-danger deleteConfirm" type="submit" value="刪除">
                </form>
              </div>
            </div>
            {% endif %}
            {# if product.image #}
            <a href="{{ product.get_absolute_url }}">
              <!--<img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.image }}">-->
              <img class="card-img-top" src="{% static 'main/img/08.jpg' %}" alt="{% static 'main/img/08.jpg' %}">
            </a>
            {# endif #}
            <div class="card-body">
              <h4 class="card-title">
                <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
              </h4>
              <h5>NT${{ product.price }}</h5>
              <p class="card-text">{{ product.content|linebreaks|truncatechars_html:40 }}</p>
              {% include 'cart/create_cart.html' with product=product %}
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      <!-- /.row -->
    </div>
    <!-- /.col-lg-12 -->
  </div>
  <!-- /.row -->
</div>
<!-- /.container -->
{% endblock %}

{% block script %}
<script src={% static 'main/js/confirm_delete.js' %}></script>
<script src={% static 'main/js/cart.js' %}></script>
{% endblock %}

product/templates/product/read_product.html
{% extends 'main/base.html' %}
{% load staticfiles %}

{% block heading %}商品資訊{% endblock %}
{% block content %}

<section class="page-section about-heading">
  <div class="container">
    <div class="row">
      <div class="col-xl-12 col-lg-10 mx-auto">
        <div class="card bg-faded rounded p-5 mb-4">
          {% if user.is_staff %}
          <div class="mb-3">
            <a class="btn btn-info" href="{% url 'product:update_product' product.id %}">修改</a>
          </div>
          {% endif %}
          <div class="mb-3">
          {% include 'cart/create_cart.html' with product=product %}
          </div>
          <h3 class="text-center">{{ product.title }}</h3>
          {# if product.image #}
          <!--<img class="rounded img-fluid my-3 mx-auto" width="800px" src="{{ product.image.url }}" alt="{{ product.image }}">-->
          <img class="rounded img-fluid my-3 mx-auto" width="800px" src="{% static 'main/img/08.jpg' %}" alt="{% static 'main/img/08.jpg' %}">
          {# endif #}
          <div class="text-center">
            <p>{{ product.content|linebreaks }}</p>
          </div>
        </div>
        <div class="card bg-faded rounded p-5">
          <h3 class="mb-5">留言區</h3>
          {% if not product.comment_set.all %}
          <p>目前此商品沒有留言</p>
          {% endif %}
          <div class="row">
          {% for comment in product.comment_set.all %}
            <div class="col-lg-2 mb-3" style="text-align:right">
              <span><b>{{ comment.user.username|truncatechars_html:14 }}</b></span>
              <p style="color:gray;"><small><strong>{{ comment.pub_time|date:'Y-m-d H:i'}}</strong></small></p>
            </div>
            <div class="col-lg-9 mb-3">
              <p>{{ comment.content }}</p>
              {% if comment.user == user %}
              <form method="post" action="{% url 'product:delete_comment' comment.id %}">
                {% csrf_token %}
                <input class="btn btn-outline-danger deleteConfirm" type="submit" value="刪除">
              </form>
              {% endif %}
              <hr>
            </div>
          {% endfor %}
          {% if user.is_authenticated %}
          <div class="col-lg-2 mb-4" style="text-align:right">
            <span><b>我要留言：</b></span>
          </div>
            <div class="col-lg-9 mb-4">
              <form class="form" method="post" action="{% url 'product:create_comment' product.id %}">
                <div class="input-group">
                  <textarea class="form-control" name="comment" placeholder="留言 ..."></textarea>
                  <div class="input-group-append">
                    {% csrf_token %}
                    <input class="btn btn-primary" type="submit" value="送出">
                  </div>
                </div>
              </form>
            </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

{% block script %}
<script src={% static 'main/js/confirm_delete.js' %}></script>
<script src={% static 'main/js/cart.js' %}></script>
{% endblock %}