cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.home, name='home'),
    path('add/', views.add_cart, name='add'),
    path('delete/<int:cart_id>/', views.delete_cart, name='delete'),
    path('update/<int:cart_id>/', views.update_cart, name='update'),
    path('update_order/', views.update_order, name='update_order'),
    path('check_order/', views.check_order, name='check_order'),
    path('check_done/', views.check_done, name="check_done"),
    path('orders/', views.order_home, name='orders'),
    path('order/<int:order_id>', views.order_read, name='order_read'),
    path('order_delete/<int:order_id>', views.order_delete, name='order_delete'),
    path('ship/', views.ship_api, name='ship')
]

coffee_shop/urls.py
from django.contrib import admin
from django.urls import path, include #re_path
from main import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.main, name='main'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('product/', include('product.urls', namespace='product')),
    path('board/', include('board.urls', namespace='board')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('contact/', include('contact.urls', namespace='contact')),
    #re_path('.*', views.main),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.urls import reverse

from account.models import User
from product.models import Product


PAY_CHOICES = (
    ('面交自取', '面交自取'),
    ('超商取貨付款', '超商取貨付款'),
)

ORDER_STATUS_CHOICES = (
    ('新建立', '新建立'),
    ('已寄出', '已寄出'),
    ('退貨', '退貨'),
)


class OrderManager(models.Manager):
    def new_or_get(self, request):
        order_id = request.session.get("order_id", None)
        qs = self.get_queryset().filter(id=order_id)
        if qs.exists():
            is_new = False
            order_obj = qs.first()
            if request.user.is_authenticated and order_obj.user is None:
                order_obj.user = request.user
                order_obj.save()
        else:
            order_obj = Order.objects.new(user=request.user)
            is_new = True
            request.session['order_id'] = order_obj.id
        return order_obj, is_new

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)


class Order(models.Model):
    user = models.ForeignKey(User, related_name='orders', on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=120, null=True, blank=True)
    phone = models.CharField(max_length=120, null=True, blank=True)
    address = models.CharField(max_length=120, null=True, blank=True)
    subtotal = models.IntegerField(default=0)
    shipping = models.IntegerField(default=0)
    total = models.IntegerField(default=0)
    pay = models.CharField(default='', choices=PAY_CHOICES, max_length=120)
    timestamp = models.DateTimeField(null=True, blank=True)
    status = models.CharField(default='新建立', choices=ORDER_STATUS_CHOICES, max_length=120)
    done = models.BooleanField(default=False)

    objects = OrderManager()

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse('cart:order_read', kwargs={'order_id': self.id})

    class Meta:
        ordering = ['-id', ]


def pre_save_order_total(sender, instance, *args, **kwargs):
    instance.subtotal = sum([cart.total for cart in instance.carts.all()])
    instance.total = instance.subtotal + instance.shipping


pre_save.connect(pre_save_order_total, sender=Order)


class CartManager(models.Manager):
    def new_or_get(self, request, order_obj, product):
        qs = self.get_queryset().filter(product=product, order=order_obj)
        if qs.exists():
            cart_obj = qs.first()
            cart_obj.quantity += 1
            cart_obj.save()
        else:
            cart_obj = self.model.objects.create(product=product, order=order_obj)
        # request.session['cart_items'] = sum([cart.quantity for cart in order_obj.carts.all()])
        return cart_obj


class Cart(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='carts', default=None)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True)
    quantity = models.IntegerField(default=1)
    total = models.IntegerField(default=0)

    objects = CartManager()

    def __str__(self):
        return str(self.id)

    class Meta:
        ordering = ['id', ]


def pre_save_cart_total(sender, instance, *args, **kwargs):
    instance.total = instance.product.price * instance.quantity


pre_save.connect(pre_save_cart_total, sender=Cart)

cart/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    name = forms.CharField(
        label='收件人姓名',
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=True
    )
    phone = forms.CharField(
        label='收件人電話',
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=True
    )
    pay = forms.CharField(
        label='付款方式',
        widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': ''}),
        required=True
    )

    class Meta:
        model = Order
        fields = ['name', 'phone', 'pay']

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

from datetime import datetime

from product.models import Product
from .models import Cart, Order
from .forms import OrderForm
# from contact.views import send_mail


def update_cart_items(request):
    order_obj, is_new = Order.objects.new_or_get(request)
    count = sum([cart.quantity for cart in order_obj.carts.all()])
    request.session['cart_items'] = count
    return count


def home(request):
    order_obj, is_new = Order.objects.new_or_get(request)
    return render(request, 'cart/cart.html', {'order': order_obj})


def add_cart(request):
    if request.method == 'GET':
        return redirect('product:product')
    # POST
    order_obj, is_new = Order.objects.new_or_get(request)
    product_id = request.POST.get('product_id')
    product = get_object_or_404(Product, id=product_id)
    cart_obj = Cart.objects.new_or_get(request, order_obj, product)
    count = update_cart_items(request)
    if request.is_ajax():
        json_data = {'cartItemCount': count}
        return JsonResponse(json_data)
    return redirect('cart:home')


def update_cart(request, cart_id):
    if request.method == 'GET':
        return redirect('cart:home')
    # POST
    cart_obj = get_object_or_404(Cart, id=cart_id)
    quantity = int(request.POST.get('quantity'))
    if quantity == 0:
        cart_obj.delete()
    else:
        cart_obj.quantity = quantity
        cart_obj.save()
    count = update_cart_items(request)
    if request.is_ajax():
        json_data = {
            'cartItemCount': count,
            'cartTotal': cart_obj.total,
            'quantity': quantity,
        }
        return JsonResponse(json_data)
    return redirect('cart:home')


def delete_cart(request, cart_id):
    if request.method == 'GET':
        return home(request)
    cart_obj = get_object_or_404(Cart, id=cart_id)
    cart_obj.delete()
    count = update_cart_items(request)
    if request.is_ajax():
        json_data = {'cartItemCount': count}
        return JsonResponse(json_data)
    return redirect('cart:home')


@login_required
@csrf_exempt
def ship_api(request):
    order_obj, is_new = Order.objects.new_or_get(request)
    order_obj.address = request.POST.get('stName')
    order_obj.save()
    return redirect('cart:update_order')


@login_required
def update_order(request):
    order_obj, is_new = Order.objects.new_or_get(request)
    # GET
    if request.method == 'GET':
        if request.GET.get('shop'):
            order_obj.shipping = 70
            order_obj.pay = '超商取貨付款'
        elif request.GET.get('self'):
            order_obj.shipping = 0
            order_obj.address = ''
            order_obj.pay = '面交自取'
        order_obj.save()
        form = OrderForm(instance=order_obj)
        return render(request, 'order/order_form.html', {'form': form, 'order': order_obj})
    # POST
    form = OrderForm(request.POST, instance=order_obj)
    if not form.is_valid():
        return render(request, 'order/order_form.html', {'form': form, 'order': order_obj})
    form.save()
    if order_obj.pay == '超商取貨付款' and not order_obj.address:
        messages.error(request, '請選擇取貨店家')
        return render(request, 'order/order_form.html', {'form': form, 'order': order_obj})
    return redirect('cart:check_order')


@login_required
def check_order(request):
    order_obj, is_new = Order.objects.new_or_get(request)
    form = OrderForm(instance=order_obj)
    if request.method == 'GET':
        return render(request, 'order/check_order.html', {'form': form, 'order': order_obj})
    order_obj.done = True
    order_obj.timestamp = datetime.now()
    order_obj.save()
    return redirect('cart:check_done')


@login_required
def check_done(request):
    order_obj, is_new = Order.objects.new_or_get(request)
    # send_mail(mail=order_obj.user.email)
    del request.session['order_id']
    del request.session['cart_items']
    return render(request, 'order/check_done.html', {'order': order_obj})


@login_required
def order_home(request):
    orders = Order.objects.filter(user=request.user).filter(done=True)
    return render(request, 'order/order_home.html', {'orders': orders})


@login_required
def order_read(request, order_id):
    order_obj = get_object_or_404(Order, id=order_id)
    return render(request, 'order/order_read.html', {'order': order_obj})


@login_required
def order_delete(request, order_id):
    if request.method == 'GET':
        return order_home(request)
    order_obj = get_object_or_404(Order, id=order_id)
    order_obj.delete()
    messages.success(request, '訂單已刪除')
    return redirect('cart:orders')

cart/templates/order/check_done.html
{% extends 'main/base.html' %}

{% block heading %}購物車結帳{% endblock %}

{% block content %}
<section class="page-section cta">
  <div class="container">
    <div class="row">
      <div class="col-xl-9 mx-auto">
        <div class="bg-faded rounded p-5">
          <h3>感謝您的訂購，您的訂單編號為: {{ order.id }}</h3>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

cart/templates/order/check_order.html
{% extends 'main/base.html' %}

{% block heading %}購物車結帳{% endblock %}

{% block content %}
<section class="page-section cta">
  <div class="container">
    <div class="row">
      <div class="col-xl-9 mx-auto">
        <div class="bg-faded rounded p-5">
          <h3 class="mb-5 text-center">請確認以下內容</h3>
          <h4 class="mb-4">訂購商品</h4>
          <table class="table mb-4">
            <thead class="thead">
            <tr>
              <th scope="col">商品名稱</th>
              <th scope="col">單價</th>
              <th scope="col">數量</th>
              <th scope="col">金額</th>
            </tr>
            </thead>
            <tbody>
              {% for cart in order.carts.all %}
              <tr>
                <td><a href="{{ cart.product.get_absolute_url }}">{{ cart.product.title }}</a></td>
                <td>{{ cart.product.price }}</td>
                <td>{{ cart.quantity }}</td>
                <td>{{ cart.total }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          <div class="text-right">
            <p><b>總價：</b> {{ order.subtotal }}元</p>
            <p><b>運費：</b> {{ order.shipping }}元</p>
            <p><b>總金額：</b> {{ order.total }}元</p>
          </div>
          <hr class="my-5">
          <h4 class="mb-4">訂購資訊</h4>
          <table class="table mb-4">
            <tbody>
              <tr>
                <td>收件人</td>
                <td>{{ order.name }}</td>
              </tr>
              <tr>
                <td>收件人電話</td>
                <td>{{ order.phone }}</td>
              </tr>
              <tr>
                <td>付款方式</td>
                <td>{{ order.pay }}</td>
              </tr>
              {% if order.address %}
              <tr>
                <td>收件門市</td>
                <td>{{ order.address }}</td>
              </tr>
              {% endif %}
            </tbody>
          </table>
          <div class="text-center mt-5">
            <form action="{% url 'cart:check_order' %}" method="post">
              {% csrf_token %}
              <a class="btn btn-primary" href="{% url 'cart:update_order' %}">上一步</a>
              <!-- Button trigger modal -->
              <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                訂購
              </button>

              <!-- Modal -->
              <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">確認訂購</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      咖啡豆烘焙商品採顧客下標後進生豆並烘焙，約需等候一至二週不等，請同意後再下標。訂單送出後不得修改，請確認訂購資訊正確再送出
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">取消</button>
                      <input class="btn btn-outline-success" type="submit" value="確認訂購">
                    </div>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

cart/templates/order/order_form.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block heading %}購物車結帳{% endblock %}

{% block content %}
<section class="page-section cta">
  <div class="container">
    <div class="row">
      <div class="col-xl-9 mx-auto">
        <div class="bg-faded rounded p-5">
          <h3 class="mb-5">購物車清單</h3>
          <table class="table table-hover mb-4">
            <thead class="thead">
            <tr>
              <th scope="col">商品名稱</th>
              <th scope="col">單價</th>
              <th scope="col">數量</th>
              <th scope="col">金額</th>
            </tr>
            </thead>
            <tbody>
              {% for cart in order.carts.all %}
              <tr>
                <td><a href="{{ cart.product.get_absolute_url }}">{{ cart.product.title }}</a></td>
                <td>{{ cart.product.price }}</td>
                <td>{{ cart.quantity }}</td>
                <td>{{ cart.total }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          <div class="text-right">
            <p><b>總價：</b> {{ order.subtotal }}元</p>
            <p><b>運費：</b> {{ order.shipping }}元</p>
            <p><b>總金額：</b> {{ order.total }}元</p>

            {% if order.pay == '超商取貨付款' %}
            <p class="inlineBlock"><b>寄送地址：</b></p>
            <form class="ship-ajax inlineBlock" action="https://map.ezship.com.tw/ezship_map_web.jsp" method="get">
              <input type="hidden" name="suID" value="ke1905ro@yahoo.com">
              <input type="hidden" name="processID" value="kiroLY">
              <input type="hidden" name="stCate" value="">
              <input type="hidden" name="stCode" value="">
              <input type="hidden" name="rtURL" value="https://a-hui-coffee.herokuapp.com/cart/ship/">
              <!--<input type="hidden" name="rtURL" value="http://127.0.0.1:8000/cart/ship/">-->
              <input type="hidden" name="webPara" value="">
              <input type="submit" value="選取店家" class="btn btn-success btn-sm">
            </form>
            {% endif %}

          </div>
          <hr class="my-5">
          <h3 class="mb-5">訂購資訊</h3>
          <form action="{% url 'cart:update_order' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="username">訂購帳號：</label>
              <input type="text" class="form-control" id="username" value="{{ order.user.username }}" readonly>
            </div>
            {{ form.as_p }}
            {% if not request.GET.self %}
            <div class="form-group" for="address">
              {% if order.address %}
              <label for="username">取貨門市：</label>
              <input type="text" class="form-control" id="address" value="{{ order.address }}" readonly>
              {% endif %}
            </div>
            {% endif %}
            <div class="text-center mt-5">
              <a href="{% url 'cart:home' %}" class="btn btn-primary">上一步</a>
              <input type="submit" class="btn btn-primary" value="下一步">
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

cart/templates/order/order_home.html
{% extends 'main/base.html' %}
{% load staticfiles %}

{% block heading %}檢視訂單{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-10 mx-auto mt-5">
      <div class="bg-faded rounded p-5">
        {% if not orders %}
        <h3>目前沒有已完成訂單</h3>
        {% else %}
        <h3>已完成訂單列表</h3>
        <hr>
        <table class="table table-hover">
          <thead class="thead">
          <tr>
            <th scope="col">訂單編號</th>
            <th scope="col">下標時間</th>
            <th scope="col">訂單總金額</th>
            <th scope="col">訂單狀態</th>
            <th scope="col"></th>
          </tr>
          </thead>
          <tbody>
          {% for order in orders %}
          <tr>
            <td><a href="{{ order.get_absolute_url }}">{{ order.id }}</a></td>
            <td><a href="{{ order.get_absolute_url }}">{{ order.timestamp }}</a></td>
            <td>{{ order.total }}</td>
            <td>{{ order.status }}</td>
            <td>
              <form action="{% url 'cart:order_delete' order.id %}" method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-outline-danger btn-sm deleteConfirm" value="取消訂單">
              </form>
            </td>
          </tr>
          {% endfor %}
          </tbody>
        </table>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block script %}
<script src={% static 'main/js/confirm_delete.js' %}></script>
<script src={% static 'main/js/base.js' %}></script>
{% endblock %}

cart/templates/order/order_read.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block heading %}檢視訂單{% endblock %}

{% block content %}
<section class="page-section cta">
  <div class="container">
    <div class="row">
      <div class="col-xl-9 mx-auto">
        <div class="bg-faded rounded p-5">
          <h3 class="mb-5">訂購資訊</h3>
          <form>
            <div class="form-group row">
              <label class="col-sm-2 col-form-label"><b>訂單編號： </b></label>
              <div class="col-sm-10">
                <input type="text" readonly class="form-control-plaintext" value="{{ order.id }}">
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-2 col-form-label"><b>訂購時間： </b></label>
              <div class="col-sm-10">
                <input type="text" readonly class="form-control-plaintext" value="{{ order.timestamp }}">
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-2 col-form-label"><b>收件人： </b></label>
              <div class="col-sm-10">
                <input type="text" readonly class="form-control-plaintext" value="{{ order.name }}">
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-2 col-form-label"><b>收件人電話： </b></label>
              <div class="col-sm-10">
                <input type="text" readonly class="form-control-plaintext" value="{{ order.phone }}">
              </div>
            </div>
            {% if order.address %}
            <div class="form-group row">
              <label class="col-sm-2 col-form-label"><b>收件地址： </b></label>
              <div class="col-sm-10">
                <input type="text" readonly class="form-control-plaintext" value="{{ order.address }}">
              </div>
            </div>
            {% endif %}
            <div class="form-group row">
              <label class="col-sm-2 col-form-label"><b>付款方式： </b></label>
              <div class="col-sm-10">
                <input type="text" readonly class="form-control-plaintext" value="{{ order.pay }}">
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-2 col-form-label"><b>訂單狀態： </b></label>
              <div class="col-sm-10">
                <input type="text" readonly class="form-control-plaintext" value="{{ order.status }}">
              </div>
            </div>
          </form>
          <hr class="my-5">
          <h3 class="mb-5">購物車內容</h3>
          <table class="table table-hover mb-4">
            <thead class="thead">
            <tr>
              <th scope="col">商品名稱</th>
              <th scope="col">單價</th>
              <th scope="col">數量</th>
              <th scope="col">金額</th>
            </tr>
            </thead>
            <tbody>
              {% for cart in order.carts.all %}
              <tr>
                <td><a href="{{ cart.product.get_absolute_url }}">{{ cart.product.title }}</a></td>
                <td>{{ cart.product.price }}</td>
                <td>{{ cart.quantity }}</td>
                <td>{{ cart.total }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          <div class="text-right">
            <p><b>總價：</b> {{ order.subtotal }}元</p>
            <p><b>運費：</b> {{ order.shipping }}元</p>
            <p><b>總金額：</b> {{ order.total }}元</p>
          </div>
          <div class="text-center">
            <form action="{% url 'cart:order_delete' order.id %}" method="post" class="mt-5">
              {% csrf_token %}
              <a href="{% url 'cart:orders' %}" class="btn btn-info">回上一頁</a>
              <input type="submit" class="btn btn-danger deleteConfirm" value="刪除此訂單">
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

{% block script %}
<script src={% static 'main/js/confirm_delete.js' %}></script>
{% endblock %}