account/urls.py
from django.urls import path
from account import views

app_name = 'account'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile')
]

board/urls.py
from django.urls import path
from board import views

app_name = 'board'
urlpatterns = [
    path('', views.board, name='board'),
    path('<int:pk>/', views.BoardDetailView.as_view(), name='board'),
    path('create_board/', views.create_board, name='create_board'),
    path('update_board/<int:board_id>/', views.update_board, name='update_board'),
    path('delete_board/<int:board_id>/', views.delete_board, name='delete_board'),
]

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.home, name='home'),
    path('add/', views.add_cart, name='add'),
    path('delete/<int:cart_id>/', views.delete_cart, name='delete'),
    path('update/<int:cart_id>/', views.update_cart, name='update'),
    path('update_order/', views.update_order, name='update_order'),
    path('check_order/', views.check_order, name='check_order'),
    path('check_done/', views.check_done, name="check_done"),
    path('orders/', views.order_home, name='orders'),
    path('order/<int:order_id>', views.order_read, name='order_read'),
    path('order_delete/<int:order_id>', views.order_delete, name='order_delete'),
    path('ship/', views.ship_api, name='ship')
]

coffee_shop/urls.py
from django.contrib import admin
from django.urls import path, include #re_path
from main import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.main, name='main'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('product/', include('product.urls', namespace='product')),
    path('board/', include('board.urls', namespace='board')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('contact/', include('contact.urls', namespace='contact')),
    #re_path('.*', views.main),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path

from . import views

app_name = 'contact'
urlpatterns = [
    path('', views.contact, name='contact'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'
urlpatterns = [
    path('', views.product, name='product'),
    path('create_product/', views.create_product, name='create_product'),
    path('read_product/<int:product_id>/', views.read_product, name='read_product'),
    path('update_product/<int:product_id>/', views.update_product, name='update_product'),
    path('delete_product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('search_product/', views.search_product, name='search_product'),
    path('create_comment/<int:product_id>/', views.create_comment, name='create_comment'),
    # path('update_comment/<int:comment_id>/', views.update_comment, name='update_comment'),
    path('delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls.base import reverse


def main(request):
    '''
    Render the main page
    '''
    return render(request, 'main/main.html')


def admin_required(func):
    def auth(request, *args, **kwargs):
        if not request.user.is_staff:
            messages.error(request, '請以管理者身份登入')
            return redirect(reverse('account:login') + '?next=' + request.get_full_path())
        return func(request, *args, **kwargs)
    return auth

main/templates/main/base.html
<!DOCTYPE html>
{% load staticfiles %}

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>A-Hui | {% block heading %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'main/css/business-casual.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/main.css' %}" rel="stylesheet" >

    <!-- fontawesome for icons -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  </head>

  <body>
    <!-- Store title -->
    <h1 class="site-heading text-center text-white d-none d-lg-block">
      <span class="site-heading-upper text-primary mb-3">咖啡烘焙坊</span>
      <span class="site-heading-lower">a-hui coffee</span>
    </h1>

    <!-- Nav bar -->
    {% include 'main/menu.html' %}

    <!-- Message box -->
    {% include 'main/messages.html' %}

    <!-- Content -->
    {% block content %}{% endblock %}

    <!-- Ajax -->
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>-->

    <!-- Bootstrap core JavaScript -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    {% block script %}{% endblock %}
  </body>

</html>

main/templates/main/main.html
{% extends 'main/base.html' %}
{% load staticfiles %}

{% block heading %}首頁{% endblock %}

{% block content %}
    <section class="page-section">
      <div class="container">
        <div class="product-item">
          <img class="product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{% static 'main/img/03.jpg' %}" width="850px">
          <div class="product-item-description d-flex mr-auto">
            <div class="bg-faded p-5 rounded">
              <p class="mb-0">
                <b>阿輝咖啡烘焙</b>為一販賣精心烘焙咖啡豆之賣場，<br>
                為維持新鮮度，均採下標後才進貨生豆並烘焙，<br>
                整個流程需花費一到兩週不等，請買家耐心等待。
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="page-section">
      <div class="container">
        <div class="product-item">
          <div class="product-item-title d-flex">
            <div class="bg-faded p-5 d-flex mr-auto rounded">
              <h2 class="section-heading mb-0">
                <span class="section-heading-lower">生豆品質</span>
              </h2>
            </div>
          </div>
          <img class="product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{% static 'main/img/04.png' %}" alt="">
          <div class="product-item-description d-flex ml-auto">
            <div class="bg-faded p-5 rounded">
              <p class="mb-0">
                本賣場所有生豆均來自<a href="http://www.bvcoffee.com.tw/about.php">宸嶧國際有限公司</a>，<br>
                該公司每批生豆均會提供國際認證標準之生豆評分，阿輝咖啡烘焙以此為參考，能穩定的掌握生豆品質。<br><br>
                生豆進貨後，阿輝烘焙均會挑選生豆，將瑕疵豆挑除後才進行烘焙，以維護品質。
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="page-section">
      <div class="container">
        <div class="product-item">
          <div class="product-item-title d-flex">
            <div class="bg-faded p-5 d-flex ml-auto rounded">
              <h2 class="section-heading mb-0">
                <span class="section-heading-lower">烘焙度與杯測</span>
              </h2>
            </div>
          </div>
          <img class="product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{% static 'main/img/00.jpg' %}" alt="">
          <div class="product-item-description d-flex mr-auto">
            <div class="bg-faded p-5 rounded">
              <p class="mb-0">
                本賣場提供的烘焙度為中淺烘焙，也可做些許客製化調整，
                請使用<a href="{% url 'contact:contact' %}">聯絡我們</a>以了解更多。
                <br>
                阿輝咖啡烘焙的烘焙手法歷經多次杯測師鑑定之後，固定下最好的流程，能提供穩定且高品質的產品。
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

main/templates/main/menu.html
{% url 'main' as main_url %}
{% url 'board:board' as board_url %}
{% url 'product:product' as product_url %}
{% url 'account:login' as login_url %}
{% url 'account:logout' as logout_url %}
{% url 'account:register' as register_url %}
{% url 'cart:home' as cart1 %}
{% url 'cart:update_order' as cart2 %}
{% url 'cart:check_order' as cart3 %}
{% url 'cart:orders' as orders %}
{% url 'account:profile' as profile_url %}
{% url 'contact:contact' as contact_url %}


<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
  <div class="container">
    <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="#">咖啡烘焙坊</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav mx-auto">
        <li class="nav-item {% if request.path == main_url %}active{% endif %} px-lg-4">
          <a class="nav-link text-expanded" href="{{ main_url }}">關於
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item {% if request.path == board_url %}active{% endif %} px-lg-4">
          <a class="nav-link text-expanded" href="{{ board_url }}">公告</a>
        </li>
        <li class="nav-item {% if request.path == product_url %}active{% endif %} px-lg-4">
          <a class="nav-link text-expanded" href="{{ product_url }}">商品</a>
        </li>
        <li class="nav-item {% if request.path == contact_url %}active{% endif %} px-lg-4">
          <a class="nav-link text-expanded" href="{{ contact_url }}">聯絡我們</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item {% if request.path == logout_url %}active{% endif %} px-lg-4">
          <a class="nav-link text-expanded" href="{{ logout_url }}">登出 ({{ user.username }})</a>
        </li>
        {% else %}
        <li class="nav-item {% if request.path == login_url or request.path == register_url %}active{% endif %} px-lg-4">
          <a class="nav-link text-expanded" href="{{ login_url }}">登入/註冊</a>
        </li>
        {% endif %}
        <li class="nav-item  px-lg-4 dropdown {% if request.path == orders or request.path == profile_url %}active{% endif %}">
          <a class="nav-link text-expanded dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            會員中心
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{ profile_url }}">我的帳號</a>
            <a class="dropdown-item" href="{{ cart1 }}">檢視購物車</a>
            <a class="dropdown-item" href="{{ orders }}">檢視/刪除訂單</a>
            <a class="dropdown-item" href="{{ contact_url }}">聯絡我們</a>
          </div>
        <li class="nav-item px-lg-4 {% if request.path == cart1 or request.path == cart2 or request.path == cart3 %}active{% endif %}">
        <a class="nav-link text-expanded" href="{{ cart1 }}"><span class="navbar-cart-count">{{ request.session.cart_items }}</span> <i class="fas fa-shopping-cart"></i></a>
        </li>
      </ul>
    </div>
  </div>
</nav>

main/templates/main/messages.html
{% for message in messages %}
  {% if message.tags == 'error' %}
  <div class="container alert alert-danger alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% else %}
  <div class="container alert alert-success alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endif %}
{% endfor %}